In [1]:
import pandas as pd
import numpy as np
from catboost import CatBoostRegressor

In [2]:
train = pd.read_csv("train.csv")
test = pd.read_csv("test.csv")

In [3]:
train.dtypes

Item_Identifier               object
Item_Weight                  float64
Item_Fat_Content              object
Item_Visibility              float64
Item_Type                     object
Item_MRP                     float64
Outlet_Identifier             object
Outlet_Establishment_Year      int64
Outlet_Size                   object
Outlet_Location_Type          object
Outlet_Type                   object
Item_Outlet_Sales            float64
dtype: object

In [4]:
test.dtypes

Item_Identifier               object
Item_Weight                  float64
Item_Fat_Content              object
Item_Visibility              float64
Item_Type                     object
Item_MRP                     float64
Outlet_Identifier             object
Outlet_Establishment_Year      int64
Outlet_Size                   object
Outlet_Location_Type          object
Outlet_Type                   object
dtype: object

In [5]:
train.isnull().sum()

Item_Identifier                 0
Item_Weight                  1463
Item_Fat_Content                0
Item_Visibility                 0
Item_Type                       0
Item_MRP                        0
Outlet_Identifier               0
Outlet_Establishment_Year       0
Outlet_Size                  2410
Outlet_Location_Type            0
Outlet_Type                     0
Item_Outlet_Sales               0
dtype: int64

In [6]:
test.isnull().sum()

Item_Identifier                 0
Item_Weight                   976
Item_Fat_Content                0
Item_Visibility                 0
Item_Type                       0
Item_MRP                        0
Outlet_Identifier               0
Outlet_Establishment_Year       0
Outlet_Size                  1606
Outlet_Location_Type            0
Outlet_Type                     0
dtype: int64

In [9]:
train

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.300,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.920,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.500,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,FDX07,19.200,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800
4,NCD19,8.930,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052
...,...,...,...,...,...,...,...,...,...,...,...,...
8518,FDF22,6.865,Low Fat,0.056783,Snack Foods,214.5218,OUT013,1987,High,Tier 3,Supermarket Type1,2778.3834
8519,FDS36,8.380,Regular,0.046982,Baking Goods,108.1570,OUT045,2002,NaN,Tier 2,Supermarket Type1,549.2850
8520,NCJ29,10.600,Low Fat,0.035186,Health and Hygiene,85.1224,OUT035,2004,Small,Tier 2,Supermarket Type1,1193.1136
8521,FDN46,7.210,Regular,0.145221,Snack Foods,103.1332,OUT018,2009,Medium,Tier 3,Supermarket Type2,1845.5976
8522,DRG01,14.800,Low Fat,0.044878,Soft Drinks,75.4670,OUT046,1997,Small,Tier 1,Supermarket Type1,765.6700

In [10]:
train[train['Item_Weight'].isnull()]

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
7,FDP10,NaN,Low Fat,0.127470,Snack Foods,107.7622,OUT027,1985,Medium,Tier 3,Supermarket Type3,4022.7636
18,DRI11,NaN,Low Fat,0.034238,Hard Drinks,113.2834,OUT027,1985,Medium,Tier 3,Supermarket Type3,2303.6680
21,FDW12,NaN,Regular,0.035400,Baking Goods,144.5444,OUT027,1985,Medium,Tier 3,Supermarket Type3,4064.0432
23,FDC37,NaN,Low Fat,0.057557,Baking Goods,107.6938,OUT019,1985,Small,Tier 1,Grocery Store,214.3876
29,FDC14,NaN,Regular,0.072222,Canned,43.6454,OUT019,1985,Small,Tier 1,Grocery Store,125.8362
...,...,...,...,...,...,...,...,...,...,...,...,...
8485,DRK37,NaN,Low Fat,0.043792,Soft Drinks,189.0530,OUT027,1985,Medium,Tier 3,Supermarket Type3,6261.8490
8487,DRG13,NaN,Low Fat,0.037006,Soft Drinks,164.7526,OUT027,1985,Medium,Tier 3,Supermarket Type3,4111.3150
8488,NCN14,NaN,Low Fat,0.091473,Others,184.6608,OUT027,1985,Medium,Tier 3,Supermarket Type3,2756.4120
8490,FDU44,NaN,Regular,0.102296,Fruits and Vegetables,162.3552,OUT019,1985,Small,Tier 1,Grocery Store,487.3656
8504,NCN18,NaN,Low Fat,0.124111,Household,111.7544,OUT027,1985,Medium,Tier 3,Supermarket Type3,4138.6128

In [20]:
train['Item_Fat_Content']=train['Item_Fat_Content'].replace({'LF':'Low Fat','low fat':'Low Fat','reg':'Regular'})

In [21]:
test['Item_Fat_Content']=test['Item_Fat_Content'].replace({'LF':'Low Fat','low fat':'Low Fat','reg':'Regular'})

In [22]:
train['Item_Weight'].fillna(train['Item_Weight'].mean(),inplace=True)

In [23]:
test['Item_Weight'].fillna(test['Item_Weight'].mean(),inplace=True)

In [24]:
train['Outlet_Size'].fillna('Medium',inplace=True)

In [25]:
test['Outlet_Size'].fillna('Medium',inplace=True)

In [29]:
train.isnull().sum()

Item_Identifier              0
Item_Weight                  0
Item_Fat_Content             0
Item_Visibility              0
Item_Type                    0
Item_MRP                     0
Outlet_Identifier            0
Outlet_Establishment_Year    0
Outlet_Size                  0
Outlet_Location_Type         0
Outlet_Type                  0
Item_Outlet_Sales            0
dtype: int64

In [30]:
test.isnull().sum()

Item_Identifier              0
Item_Weight                  0
Item_Fat_Content             0
Item_Visibility              0
Item_Type                    0
Item_MRP                     0
Outlet_Identifier            0
Outlet_Establishment_Year    0
Outlet_Size                  0
Outlet_Location_Type         0
Outlet_Type                  0
dtype: int64

In [31]:
train['Item_Visibility'].fillna(train['Item_Visibility'].median(),inplace=True)

In [32]:
test['Item_Visibility'].fillna(test['Item_Visibility'].median(),inplace=True)

In [34]:
train['New_Item_Type']=train['Item_Identifier'].apply(lambda x: x[0:2])

In [35]:
train['New_Item_Type']= train['New_Item_Type'].map({"FD":"Food","NC":"Non-Consumable",'DR':'Drinks'})

In [36]:
test['New_Item_Type']=test['Item_Identifier'].apply(lambda x: x[0:2])

In [37]:
test['New_Item_Type']= test['New_Item_Type'].map({"FD":"Food","NC":"Non-Consumable",'DR':'Drinks'})

In [39]:
train.loc[train['New_Item_Type']== "Non-Consumable",'Item_Fat_Content']= "Non-Edible"

In [40]:
test.loc[test['New_Item_Type']== "Non-Consumable",'Item_Fat_Content']= "Non-Edible"

In [41]:
train

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales,New_Item_Type
0,FDA15,9.300,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380,Food
1,DRC01,5.920,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228,Drinks
2,FDN15,17.500,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700,Food
3,FDX07,19.200,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,Medium,Tier 3,Grocery Store,732.3800,Food
4,NCD19,8.930,Non-Edible,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052,Non-Consumable
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8518,FDF22,6.865,Low Fat,0.056783,Snack Foods,214.5218,OUT013,1987,High,Tier 3,Supermarket Type1,2778.3834,Food
8519,FDS36,8.380,Regular,0.046982,Baking Goods,108.1570,OUT045,2002,Medium,Tier 2,Supermarket Type1,549.2850,Food
8520,NCJ29,10.600,Non-Edible,0.035186,Health and Hygiene,85.1224,OUT035,2004,Small,Tier 2,Supermarket Type1,1193.1136,Non-Consumable
8521,FDN46,7.210,Regular,0.145221,Snack Foods,103.1332,OUT018,2009,Medium,Tier 3,Supermarket Type2,1845.5976,Food
8522,DRG01,14.800,Low Fat,0.044878,Soft Drinks,75.4670,OUT046,1997,Small,Tier 1,Supermarket Type1,765.6700,Drinks

In [42]:
X= train.drop(['Item_Type','Outlet_Establishment_Year','Item_Identifier','Outlet_Identifier','Item_Outlet_Sales'],axis=1)

In [43]:
X

,Item_Weight,Item_Fat_Content,Item_Visibility,Item_MRP,Outlet_Size,Outlet_Location_Type,Outlet_Type,New_Item_Type
0,9.300,Low Fat,0.016047,249.8092,Medium,Tier 1,Supermarket Type1,Food
1,5.920,Regular,0.019278,48.2692,Medium,Tier 3,Supermarket Type2,Drinks
2,17.500,Low Fat,0.016760,141.6180,Medium,Tier 1,Supermarket Type1,Food
3,19.200,Regular,0.000000,182.0950,Medium,Tier 3,Grocery Store,Food
4,8.930,Non-Edible,0.000000,53.8614,High,Tier 3,Supermarket Type1,Non-Consumable
...,...,...,...,...,...,...,...,...
8518,6.865,Low Fat,0.056783,214.5218,High,Tier 3,Supermarket Type1,Food
8519,8.380,Regular,0.046982,108.1570,Medium,Tier 2,Supermarket Type1,Food
8520,10.600,Non-Edible,0.035186,85.1224,Small,Tier 2,Supermarket Type1,Non-Consumable
8521,7.210,Regular,0.145221,103.1332,Medium,Tier 3,Supermarket Type2,Food
8522,14.800,Low Fat,0.044878,75.4670,Small,Tier 1,Supermarket Type1,Drinks

In [44]:
y=train['Item_Outlet_Sales']

In [45]:
y

0       3735.1380
1        443.4228
2       2097.2700
3        732.3800
4        994.7052
          ...
8518    2778.3834
8519     549.2850
8520    1193.1136
8521    1845.5976
8522     765.6700
Name: Item_Outlet_Sales, Length: 8523, dtype: float64

In [46]:
test

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,New_Item_Type
0,FDW58,20.750000,Low Fat,0.007565,Snack Foods,107.8622,OUT049,1999,Medium,Tier 1,Supermarket Type1,Food
1,FDW14,8.300000,Regular,0.038428,Dairy,87.3198,OUT017,2007,Medium,Tier 2,Supermarket Type1,Food
2,NCN55,14.600000,Non-Edible,0.099575,Others,241.7538,OUT010,1998,Medium,Tier 3,Grocery Store,Non-Consumable
3,FDQ58,7.315000,Low Fat,0.015388,Snack Foods,155.0340,OUT017,2007,Medium,Tier 2,Supermarket Type1,Food
4,FDY38,12.695633,Regular,0.118599,Dairy,234.2300,OUT027,1985,Medium,Tier 3,Supermarket Type3,Food
...,...,...,...,...,...,...,...,...,...,...,...,...
5676,FDB58,10.500000,Regular,0.013496,Snack Foods,141.3154,OUT046,1997,Small,Tier 1,Supermarket Type1,Food
5677,FDD47,7.600000,Regular,0.142991,Starchy Foods,169.1448,OUT018,2009,Medium,Tier 3,Supermarket Type2,Food
5678,NCO17,10.000000,Non-Edible,0.073529,Health and Hygiene,118.7440,OUT045,2002,Medium,Tier 2,Supermarket Type1,Non-Consumable
5679,FDJ26,15.300000,Regular,0.000000,Canned,214.6218,OUT017,2007,Medium,Tier 2,Supermarket Type1,Food
5680,FDU37,9.500000,Regular,0.104720,Canned,79.7960,OUT045,2002,Medium,Tier 2,Supermarket Type1,Food

In [49]:
new_test= test.drop(['Item_Type','Outlet_Establishment_Year','Item_Identifier','Outlet_Identifier'],axis=1)

In [50]:
new_test

,Item_Weight,Item_Fat_Content,Item_Visibility,Item_MRP,Outlet_Size,Outlet_Location_Type,Outlet_Type,New_Item_Type
0,20.750000,Low Fat,0.007565,107.8622,Medium,Tier 1,Supermarket Type1,Food
1,8.300000,Regular,0.038428,87.3198,Medium,Tier 2,Supermarket Type1,Food
2,14.600000,Non-Edible,0.099575,241.7538,Medium,Tier 3,Grocery Store,Non-Consumable
3,7.315000,Low Fat,0.015388,155.0340,Medium,Tier 2,Supermarket Type1,Food
4,12.695633,Regular,0.118599,234.2300,Medium,Tier 3,Supermarket Type3,Food
...,...,...,...,...,...,...,...,...
5676,10.500000,Regular,0.013496,141.3154,Small,Tier 1,Supermarket Type1,Food
5677,7.600000,Regular,0.142991,169.1448,Medium,Tier 3,Supermarket Type2,Food
5678,10.000000,Non-Edible,0.073529,118.7440,Medium,Tier 2,Supermarket Type1,Non-Consumable
5679,15.300000,Regular,0.000000,214.6218,Medium,Tier 2,Supermarket Type1,Food
5680,9.500000,Regular,0.104720,79.7960,Medium,Tier 2,Supermarket Type1,Food

In [51]:
from sklearn.model_selection import train_test_split

In [52]:
X_train, X_validation, y_train, y_validation = train_test_split(X, y, train_size=0.7, random_state=101)

In [53]:
categorical_features_indices = np.where(X.dtypes != np.float)[0]

In [54]:
categorical_features_indices

array([1, 4, 5, 6, 7], dtype=int64)

In [55]:
from catboost import CatBoostRegressor

In [56]:
model=CatBoostRegressor(iterations=50, depth=3, learning_rate=0.1, loss_function='RMSE')

In [57]:
model.fit(X_train, y_train,cat_features=categorical_features_indices,eval_set=(X_validation, y_validation),plot=True)

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

0:	learn: 1684.7219859	test: 1595.7876968	best: 1595.7876968 (0)	total: 70.7ms	remaining: 3.46s
1:	learn: 1643.0465598	test: 1554.3176115	best: 1554.3176115 (1)	total: 83.1ms	remaining: 1.99s
2:	learn: 1606.4012859	test: 1517.4663676	best: 1517.4663676 (2)	total: 95.5ms	remaining: 1.5s
3:	learn: 1535.9174004	test: 1448.7949330	best: 1448.7949330 (3)	total: 109ms	remaining: 1.26s
4:	learn: 1476.1923745	test: 1391.6834722	best: 1391.6834722 (4)	total: 121ms	remaining: 1.09s
5:	learn: 1425.0113220	test: 1340.0579514	best: 1340.0579514 (5)	total: 135ms	remaining: 989ms
6:	learn: 1381.0798408	test: 1296.7776287	best: 1296.7776287 (6)	total: 150ms	remaining: 919ms
7:	learn: 1344.8385637	test: 1260.7473869	best: 1260.7473869 (7)	total: 165ms	remaining: 864ms
8:	learn: 1311.8341570	test: 1228.7708553	best: 1228.7708553 (8)	total: 178ms	remaining: 810ms
9:	learn: 1283.8749507	test: 1201.9714197	best: 1201.9714197 (9)	total: 190ms	remaining: 759ms
10:	learn: 1261.0822444	test: 1179.5872271	best: 1179.5872271 (10)	total: 203ms	remaining: 721ms
11:	learn: 1240.6926811	test: 1158.6193166	best: 1158.6193166 (11)	total: 219ms	remaining: 693ms
12:	learn: 1221.6400027	test: 1139.5695504	best: 1139.5695504 (12)	total: 232ms	remaining: 661ms
13:	learn: 1205.5124168	test: 1123.2293070	best: 1123.2293070 (13)	total: 247ms	remaining: 636ms
14:	learn: 1191.9211132	test: 1109.4249192	best: 1109.4249192 (14)	total: 262ms	remaining: 612ms
15:	learn: 1180.6612201	test: 1098.0995396	best: 1098.0995396 (15)	total: 275ms	remaining: 584ms
16:	learn: 1169.7510520	test: 1087.3376090	best: 1087.3376090 (16)	total: 287ms	remaining: 556ms
17:	learn: 1160.7349928	test: 1078.5222850	best: 1078.5222850 (17)	total: 298ms	remaining: 531ms
18:	learn: 1153.4148641	test: 1071.9418292	best: 1071.9418292 (18)	total: 310ms	remaining: 506ms
19:	learn: 1146.7856924	test: 1066.1084059	best: 1066.1084059 (19)	total: 322ms	remaining: 483ms
20:	learn: 1140.2285787	test: 1059.7662667	best: 1059.7662667 (20)	total: 333ms	remaining: 461ms
21:	learn: 1135.0000712	test: 1054.1519858	best: 1054.1519858 (21)	total: 347ms	remaining: 442ms
22:	learn: 1130.4160241	test: 1049.5130891	best: 1049.5130891 (22)	total: 359ms	remaining: 422ms
23:	learn: 1126.7173025	test: 1046.0607333	best: 1046.0607333 (23)	total: 371ms	remaining: 402ms
24:	learn: 1123.6022441	test: 1042.5787232	best: 1042.5787232 (24)	total: 384ms	remaining: 384ms
25:	learn: 1120.4450785	test: 1039.7197640	best: 1039.7197640 (25)	total: 396ms	remaining: 366ms
26:	learn: 1117.5471341	test: 1036.8547614	best: 1036.8547614 (26)	total: 409ms	remaining: 348ms
27:	learn: 1115.1652813	test: 1034.8154954	best: 1034.8154954 (27)	total: 422ms	remaining: 331ms
28:	learn: 1112.8426146	test: 1032.4688085	best: 1032.4688085 (28)	total: 435ms	remaining: 315ms
29:	learn: 1111.7331317	test: 1031.1953196	best: 1031.1953196 (29)	total: 447ms	remaining: 298ms
30:	learn: 1110.2765939	test: 1029.7491027	best: 1029.7491027 (30)	total: 459ms	remaining: 281ms
31:	learn: 1109.1767284	test: 1028.9287045	best: 1028.9287045 (31)	total: 470ms	remaining: 265ms
32:	learn: 1108.1301459	test: 1027.8136567	best: 1027.8136567 (32)	total: 482ms	remaining: 248ms
33:	learn: 1107.1921155	test: 1027.0051228	best: 1027.0051228 (33)	total: 494ms	remaining: 232ms
34:	learn: 1106.2755619	test: 1025.9719948	best: 1025.9719948 (34)	total: 505ms	remaining: 217ms
35:	learn: 1105.7086262	test: 1025.4967869	best: 1025.4967869 (35)	total: 517ms	remaining: 201ms
36:	learn: 1105.0836060	test: 1025.0487538	best: 1025.0487538 (36)	total: 530ms	remaining: 186ms
37:	learn: 1104.1600671	test: 1024.3509288	best: 1024.3509288 (37)	total: 542ms	remaining: 171ms
38:	learn: 1103.2863032	test: 1023.3243824	best: 1023.3243824 (38)	total: 555ms	remaining: 157ms
39:	learn: 1102.7534835	test: 1022.9797349	best: 1022.9797349 (39)	total: 568ms	remaining: 142ms
40:	learn: 1101.8207061	test: 1022.7159034	best: 1022.7159034 (40)	total: 581ms	remaining: 128ms
41:	learn: 1101.3996892	test: 1022.2612693	best: 1022.2612693 (41)	total: 593ms	remaining: 113ms
42:	learn: 1101.1160392	test: 1021.9349687	best: 1021.9349687 (42)	total: 605ms	remaining: 98.5ms
43:	learn: 1100.9625128	test: 1021.8887429	best: 1021.8887429 (43)	total: 617ms	remaining: 84.2ms
44:	learn: 1100.7826454	test: 1021.6616316	best: 1021.6616316 (44)	total: 631ms	remaining: 70.1ms
45:	learn: 1100.2251585	test: 1021.3395160	best: 1021.3395160 (45)	total: 644ms	remaining: 56ms
46:	learn: 1099.8776160	test: 1021.0902396	best: 1021.0902396 (46)	total: 658ms	remaining: 42ms
47:	learn: 1099.7585730	test: 1020.9934802	best: 1020.9934802 (47)	total: 671ms	remaining: 27.9ms
48:	learn: 1099.5862189	test: 1020.9412547	best: 1020.9412547 (48)	total: 683ms	remaining: 13.9ms
49:	learn: 1099.5710407	test: 1020.9403635	best: 1020.9403635 (49)	total: 696ms	remaining: 0us

bestTest = 1020.940363
bestIteration = 49

In [58]:
submission = pd.DataFrame()

In [59]:
submission['Item_Identifier'] = test['Item_Identifier']

In [60]:
submission['Outlet_Identifier'] = test['Outlet_Identifier']

In [62]:
submission['Item_Outlet_Sales'] = model.predict(new_test)

In [63]:
submission.to_csv("Submission.csv")

In [64]:
submission

     Item_Identifier Outlet_Identifier  Item_Outlet_Sales
0              FDW58            OUT049        1684.008121
1              FDW14            OUT017        1450.034952
2              NCN55            OUT010         773.260660
3              FDQ58            OUT017        2420.272793
4              FDY38            OUT027        5861.413306
...              ...               ...                ...
5676           FDB58            OUT046        2209.897440
5677           FDD47            OUT018        2427.683232
5678           NCO17            OUT045        1937.142785
5679           FDJ26            OUT017        3454.796957
5680           FDU37            OUT045        1277.538890

[5681 rows x 3 columns]